### ISSUE TITLE
HINT model.

### ISSUE THREAD

**Issue by zpallin** [codeforsanjose/MobilityMap#3]
Hints will be the primary function of our site. Using backbone.js.

It will need the following models and perhaps more:
- **hint**: the core item, its title, and id mappings to other models. (cateogory,issue)
- **category**: this is the broad categorical hint "type"
- **issue**: issue type is dependent on category, but can exist across multiple categories. This second prong helps narrow peoples' issues down.
- **comment**: Comments are gathered on one table for now. The ID of the hint it is associated with is stored in the comment and a join is performed to display the comments with the hint.

This is all going to be a hack of the already existing "Place" class that is used in the MVC model designed in the sa_wb directory. In order to modify this, some deeper understanding into the Backbone and Handlebars system works together is necessary. Fortunately, aside from Javascript being different than Python, it is essentially the same type of logic used in Django.

Additionally, we need an admin view where we can edit and control these models to easy update them instead of the more manual method that is used currently by the system. As it is now, "flavors" are stored in "src/flavors" and contain a list of all of the places that are used. This gets generated on the front end when someone accesses a site.

Key scripts in changing and editing "places" to convert it into "hints" are in "src/sa_web/static/js/models.js" and "src/sa_web/static/js/views/app-view.js"

**Comment by zpallin** [comment]
It seems these changes break the submission ability.

**Comment by wilsonww** [comment]
Committed two changes to this issue. When we refactored location_type to hint_type, the form input was providing hint_type but the conditional eval code was looking for location_type. Took the easy way out and changed the single hint_type to location_type. 

Also fixed side_walk similar naming issue.
