### ISSUE TITLE
CSS and styling update

### ISSUE THREAD

**Issue by zpallin** [codeforsanjose/MobilityMap#5]
Create a format for our site that fits the needs of our userbase.
1. eliminate clutter
2. pick a colorscheme that works
3. make sure that styling is done in a modular way that is easy to edit later -- such as creating a NEW stylesheet rather than editing an existing one.
4. Don't dip into functionality. Focused on making what we have now look good, and only remove stuff that has no purpose being there.

**Comment by wilsonww** [comment]
Let's go with http://www.colourlovers.com/palette/3870479/I_Witnessed_Majesty

**Comment by zpallin** [comment]
It'll work!
