### ISSUE TITLE
Make a new mobility map flavor

### ISSUE THREAD

**Issue by zpallin** [codeforsanjose/MobilityMap#8]
We don't want to edit defaults, so we make our own by copying to "flavors/mobilitymap"

**Comment by wilsonww** [comment]
For future reference. Because we gitignore local_settings.py, we need to remember to change the defaultflavor to mobilitymap. We can probably commit this in local_settings.py.template

**Comment by zpallin** [comment]
Good call.

**Comment by wilsonww** [comment]
We've done this

**Comment by zpallin** [comment]
Yay! Where? Can you link to it? @wilsonww
